const nextGenConvertedComponents = [
  'AccordionGridGroup',
  'AccordionGroup',
  'ArrayField',
  'AstroProvider',
  'Avatar',
  'Badge',
  'Base Components',
  'Breadcrumbs',
  'Button',
  'ButtonBar',
  'Callout',
  'Card',
  'CheckboxField',
  'CodeView',
  'ColorField',
  'ComboBoxField',
  'CopyText',
  'DataTable',
  'EnvironmentBreadcrumb',
  'GridList',
  'HelpHint',
  'Icon',
  'IconBadge',
  'IconButton',
  'IconWrapper',
  'ImageUploadField',
  'Loader',
  'Link',
  'LinkSelectField',
  'ListView',
  'ListViewItem',
  'Message',
  'Messages',
  'Modal',
  'MultiValuesField',
  'MultivaluesField',
  'NavBar',
  'NavList',
  'NavigationHeader',
  'NextGen ListViewItem',
  'NumberField',
  'OverlayPanel',
  'PageHeader',
  'Pagination',
  'PanelHeader',
  'PasswordField',
  'PopoverMenu',
  'ProgressBar',
  'RadioField',
  'RadioGroupField',
  'RangeCalendar',
  'RequirementsList',
  'RockerButtonGroup',
  'SearchField',
  'SelectField',
  'Skeleton',
  'SliderField',
  'Stepper',
  'Sticker Sheet',
  'SwitchField',
  'StatusIcon',
  'Table',
  'TableBase',
  'Tabs',
  'Text',
  'TextAreaField',
  'TextField',
  'TooltipTrigger',
  'ArrayField',
  'ColorField',
  'LinkSelectField',
  'NumberField',
  'SwitchField',
  'Base Components',
  'SliderField',
  'ServerErrorBoundary',
  'Avatar',
  'Box',
  'TimeField',
];

export const componentSpecificNextGenBlacklist = {
  AstroProvider: ['Default', 'With Custom Theme Override'],
  Messages: ['Customization'],
  PasswordField: ['Success'],
  TextField: ['Success'],
  OverlayPanel: ['Expandable'],
  DataTable: ['Default'],
  Text: ['Default'],
  Tabs: ['Vertical Orientation'],
  AccordionGridGroup: ['Default', 'Accordion With Inputs', 'Controlled'],
};

export const astroBlacklistStory = {
  AccordionGridGroup: [
    'Onyx Default',
  ],
  DataTable: [
    'Onyx Default',
  ],
  NavBar: [
    'Onyx Default',
  ],
  SearchField: [
    'Onyx With Filter',
  ],
  Callout: [
    'Customizations',
  ],
  CodeView: [
    'Light',
  ],
  StatusIcon: [
    'Default',
    'In Rocker Button',
  ],
  Avatar: [
    'Size Variation',
    'Color Variation',
    'Icon Variation',
    'Square Variation',
    'Logo Variation',
  ],
  Text: [
    'Onyx',
  ],
  Loader: [
    'Circular',
    'Custom Circular',
  ],
  Card: [
    'With Shadow',
  ],
};

export const nextGenOnlyComponents = [
  'NavigationHeader',
  'Prompt',
  'AI Panel',
  'Response',
  'Suggestions',
  'Prompt Input',
  'Footer',
  'Onyx Input Patterns',
];

export default nextGenConvertedComponents;
