const nextGenConvertedComponents = [
  'AccordionGridGroup',
  'AccordionGroup',
  'ArrayField',
  'AstroProvider',
  'Avatar',
  'Badge',
  'Base Components',
  'Breadcrumbs',
  'Button',
  'ButtonBar',
  'Callout',
  'Card',
  'CheckboxField',
  'CodeView',
  'ColorField',
  'ComboBoxField',
  'CopyText',
  'DataTable',
  'EnvironmentBreadcrumb',
  'GridList',
  'HelpHint',
  'Icon',
  'IconBadge',
  'IconButton',
  'IconWrapper',
  'ImageUploadField',
  'Loader',
  'Link',
  'LinkSelectField',
  'ListView',
  'ListViewItem',
  'Message',
  'Messages',
  'Modal',
  'MultiValuesField',
  'MultivaluesField',
  'NavBar',
  'NavigationHeader',
  'NextGen ListViewItem',
  'NumberField',
  'OverlayPanel',
  'PageHeader',
  'Pagination',
  'PanelHeader',
  'PasswordField',
  'PopoverMenu',
  'ProgressBar',
  'RadioField',
  'RadioGroupField',
  'RequirementsList',
  'RockerButtonGroup',
  'SearchField',
  'SelectField',
  'Skeleton',
  'SliderField',
  'Stepper',
  'Sticker Sheet',
  'SwitchField',
  'StatusIcon',
  'Table',
  'TableBase',
  'Tabs',
  'Text',
  'TextAreaField',
  'TextField',
  'TooltipTrigger',
  'ArrayField',
  'ColorField',
  'LinkSelectField',
  'NumberField',
  'SwitchField',
  'Base Components',
  'SliderField',
  'ServerErrorBoundary',
  'Avatar',
];

export const componentSpecificNextGenBlacklist = {
  AstroProvider: ['Default', 'With Custom Theme Override'],
  Messages: ['Customization'],
  PasswordField: ['Success'],
  TextField: ['Success'],
  OverlayPanel: ['Expandable'],
  DataTable: ['Default'],
  Text: ['Default'],
  Tabs: ['Vertical Orientation'],
};

export const astroBlacklistStory = {
  DataTable: ['Onyx Default'],
  NavBar: ['Onyx Default'],
  SearchField: ['Onyx With Filter'],
  Callout: ['Customizations'],
  StatusIcon: ['Default', 'In Rocker Button'],
  Avatar: [
    'With Size Variation',
    'With Color Variation',
    'With Icon Variation',
    'With Square Variation',
  ],
  Text: ['Onyx'],
  Loader: ['Circular', 'CustomCircular'],
};

export const nextGenOnlyComponents = [
  'NavigationHeader',
  'Prompt',
  'AI Panel',
  'Response',
  'Suggestions',
  'Prompt Input',
  'Footer',
];

export default nextGenConvertedComponents;
