npmRegistryServer: "https://art01.corp.pingidentity.com/artifactory/api/npm/npm-virtual/"

yarnPath: .yarn/releases/yarn-3.2.4.cjs

packageExtensions:
  "@babel/plugin-transform-spread@*":
    dependencies:
      "@babel/core": "*"
  "@babel/preset-react@*":
    dependencies:
      "@babel/core": "*"
  "@babel/cli@*":
    dependencies:
      "@babel/core": "*"
  "@babel/preset-env@*":
    dependencies:
      "@babel/core": "*"
  "@babel/plugin-transform-runtime@*":
    dependencies:
      "@babel/core": "*"
  "@babel/plugin-proposal-class-properties@*":
    dependencies:
      "@babel/core": "*"
  "@emotion/babel-preset-css-prop@*":
    dependencies:
      "@babel/core": "*"
  "@emotion/styled@*":
    dependencies:
      "@emotion/react": "*"
  "@pingux/end-user@*":
    dependencies:
      "prop-types": "*"
  "@react-aria/dialog@*":
    dependencies:
      "react-dom": "^16.13.1"
  "@react-aria/list@*":
    dependencies:
      "react-dom": "^16.13.1"
  "@react-spectrum/dnd@*":
    dependencies:
      "react-dom": "^16.13.1"
  "@react-types/list@*":
    dependencies:
      "react-dom": "^16.13.1"
      "@react-spectrum/provider": "*"
  "@storybook/addon-console@*":
    dependencies:
      "prop-types": "*"
  "@storybook/addon-docs@*":
    dependencies:
      "@babel/core": "*"
      "webpack": "^4"
  "@storybook/addon-knobs@*":
    dependencies:
      "@storybook/addons": "*"
      "@storybook/api": "*"
      "@storybook/client-api": "*"
      "@storybook/components": "*"
      "@storybook/core": "*"
      "@storybook/core-events": "*"
      "@storybook/theming": "*"
  "@storybook/builder-webpack4@*":
    dependencies:
      "sass-loader": "^10.2.0"
  "@storybook/core@*":
    dependencies:
      "webpack": "^4"
  "@storybook/docs-tools@*":
    dependencies:
      "react": "^16.8.6"
      "react-dom": "^16.13.1"
  "@storybook/mdx1-csf@*":
    dependencies:
      "@babel/core": "*"
  "@storybook/telemetry@*":
    dependencies:
      "react": "^16.8.6"
      "react-dom": "^16.13.1"
  "@storybook/react@*":
    dependencies:
      "require-from-string": "*"
      "react-dom": "^16.13.1"
  "@testing-library/react-hooks@*":
    dependencies:
      "react-test-renderer": "*"
  "@testing-library/user-event@*":
    dependencies:
      "@testing-library/dom": "*"
  "@testing-library/react@*":
    dependencies:
      "core-js": "*"
      "react-dom": "^16.13.1"
  "@theme-ui/css@*":
    dependencies:
      "react": "^16.8.6"
  "@whitespace/storybook-addon-html@*":
    dependencies:
      "@storybook/addons": "*"
  "babel-loader@*":
    dependencies:
      "webpack": "^4"
  "eslint@*":
    dependencies:
      "estraverse": "*"
      "escope": "*"
  "extract-text-webpack-plugin@*":
    dependencies:
      "webpack": "^4"
  "html-webpack-plugin@*":
    dependencies:
      "babel-loader": "*"
      "webpack": "^4"
    peerDependencies:
      "@babel/core": "*"
  "react-hot-loader@*":
    dependencies:
      "react": "^16.8.6"
      "react-dom": "^16.13.1"
  "rjsf-conditionals@*":
    dependencies:
      "core-js": "*"
      "json-rules-engine-simplified": "*"
      "@babel/runtime-corejs2": "*"
  "sass-loader@*":
    dependencies:
      "sass": "*"
  "styled-components@*":
    dependencies:
      "react-is": "*"
  "theme-ui@*":
    dependencies:
      "@emotion/react": "^11.10.5"
  "@nrwl/devkit@*":
    dependencies:
      "nx": "*"
  "@phenomnomnominal/tsquery@*":
    dependencies:
      "typescript": "*"
  "@react-aria/grid@*":
    dependencies:
      "react-dom": "^16.13.1"
