# Create node_modules cache for reuse downstream
build-dependencies:
  extends: 
    - .base-job
  stage: build-dependencies
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - yarn.lock
<<<<<<< HEAD
=======
    # Run automatically for all commits on develop and master
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == "master"'
>>>>>>> develop
  script: 
    - yarn --frozen-lockfile
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
    policy: push
    untracked: true
