.base-build-test-lint:
  stage: build-test-lint
  tags:
    - pingux-runner
  image: $STABLE_IMAGE
  interruptible: true

# Create node_modules artifact for reuse downstream
build-dependencies-commit-lint:
  extends: 
    - .base-build-test-lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # Run automatically for merge trains to develop and master
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_EVENT_TYPE == "merge_train" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^(master|develop)/'
    # Run automatically for all commits on develop and master
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == "master"'
  before_script:
    - yarn --frozen-lockfile
  script:
    - bash commit_lint.sh
  artifacts:
    untracked: true
    paths:
      - node_modules/
    expire_in: 1 week

# Double check astro build -- consider removing
build-no-lockfile:
  extends: .base-build-test-lint
  rules:
    # Require manuel trigger for merge trains to develop and master if there has been changes to Astro
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_EVENT_TYPE == "merge_train" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^(master|develop)/'
      changes:
        - "packages/astro/**/*"
      when: manual
      allow_failure: false
  script:
    - yarn --no-lockfile --ignore-engines
    - lerna run build --scope @pingux/astro
