deploy_prerelease:
  extends:
    - .base-job
  stage: deploy
  interruptible: false
  rules:
    # Deploy develop branch via Jenkins API *UNLESS* the last commit was an alpha build.
    # This prevents loops.
    - if: '$CI_COMMIT_BRANCH == "develop" && $CI_COMMIT_TITLE != "chore(release): publish alpha build" && $CI_COMMIT_TITLE != "Merge branch ''master'' into develop"'
  script:
    - curl -X POST -u "elijahcooper:$JENKINS_API_TOKEN" "https://jenkins-icecream.pingdev.tools/job/devtools-controlled-pipelines/job/PingOne/job/UI-Library/job/pingux-monorepo-build/job/$CI_COMMIT_BRANCH/build"

deploy_astro_v2_prerelease:
  extends:
    - .base-job
  stage: deploy
  interruptible: false
  rules:
    # Deploy astro-v2 branch via Jenkins API *UNLESS* the last commit was an alpha build.
    # This prevents loops.
    - if: '$CI_COMMIT_BRANCH == "astro-v2"'
      when: manual
  script:
    - curl -X POST -u "elijahcooper:$JENKINS_API_TOKEN" "https://jenkins-icecream.pingdev.tools/job/devtools-controlled-pipelines/job/PingOne/job/UI-Library/job/pingux-monorepo-build/job/$CI_COMMIT_BRANCH/build"

deploy_release:
  extends:
    - .base-job
  stage: deploy
  interruptible: false
  rules:
    # Deploy master branch via Jenkins API *UNLESS* the last commit was a stable build.
    # This prevents loops.
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_COMMIT_TITLE != "chore(release): publish stable build"'
  script:
    - curl -X POST -u "elijahcooper:$JENKINS_API_TOKEN" "https://jenkins-icecream.pingdev.tools/job/devtools-controlled-pipelines/job/PingOne/job/UI-Library/job/generic-release/buildWithParameters"
