backstop:
  extends:
    - .base-job
  stage: screenshot
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - packages/ui-library/**/*
  # Temporarily disabled to run in the pipeline due to error. In the meantime, backstop needs to be run locally.
  # Ref: [UIP-5633] https://jira.pingidentity.com/browse/UIP-5633
  script:
    # - lerna run demo --scope ui-library
    # - lerna run backstop-ci
    - echo "Run backstop locally."
  when: manual

chromatic:
  extends:
    - .base-job
  stage: screenshot
  variables:
    CHROMATIC_FLAGS: "--project-token=$CHROMATIC_PROJECT_TOKEN --build-script-name demo --scope astro"
  rules:
    # Run automatically for merge trains to develop and master
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_EVENT_TYPE == "merge_train" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^(master|develop)/'
      changes:
        - packages/astro/**/*
    # Required manual trigger for merge requests against master or develop
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^(master|develop)/'
      changes:
        - packages/astro/**/*
      when: manual
      allow_failure: false
    # Optional manual trigger for merge requests against branches other than master and develop
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME !~ /^(master|develop)/'
      changes:
        - packages/astro/**/*
      when: manual
      allow_failure: true
    # Run automatically for all commits on develop and master, plus auto-accept any changes
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == "master"'
      changes:
        - packages/astro/**/*
      variables:
        CHROMATIC_FLAGS: "--auto-accept-changes --project-token=$CHROMATIC_PROJECT_TOKEN --build-script-name demo --scope astro"
  script:
    - lerna run chromatic -- $CHROMATIC_FLAGS
