backstop:
  extends:
    - .base-job
  stage: screenshot
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - packages/ui-library/**/*
  # Temporarily disabled to run in the pipeline due to error. In the meantime, backstop needs to be run locally.
  # Ref: [UIP-5633] https://jira.pingidentity.com/browse/UIP-5633
  script:
    # - lerna run demo --scope ui-library
    # - lerna run backstop-ci
    - echo "Run backstop locally."
  when: manual

chromatic:
  extends:
    - .base-job
  stage: screenshot
  variables:
    CHROMATIC_FLAGS: "--project-token=$CHROMATIC_PROJECT_TOKEN --build-script-name demo --scope astro"
  when: manual
  script:
    - lerna run chromatic -- $CHROMATIC_FLAGS
