import AccountIcon from '@pingux/mdi-react/AccountIcon';
import FormSelectIcon from '@pingux/mdi-react/FormSelectIcon';

export const items = [
  {
    email: 'dburkitt5@columbia.edu',
    firstName: 'Nicola',
    lastName: 'Burkitt',
    hasIcon: true,
    icon: AccountIcon,
    linkProps: { href: 'https://pingidentity.com/' },
  },
  {
    email: 'idixie2@elegantthemes.com',
    firstName: 'Cacilia',
    lastName: 'Dixie',
    hasIcon: true,
    icon: FormSelectIcon,
    linkProps: { href: 'https://pingidentity.com/' },
  },
  {
    email: 'dfowler0@rambler.ru',
    firstName: 'Stavro',
    lastName: 'Fowler',
    hasIcon: true,
    icon: AccountIcon,
    linkProps: { href: 'https://pingidentity.com/' },
  },
  {
    email: 'jgolde8@jimdo.com',
    firstName: 'Celisse',
    lastName: 'Golde',
    hasIcon: true,
    icon: FormSelectIcon,
  },
  {
    email: 'shearst9@answers.com',
    firstName: 'Jeth',
    lastName: 'Hearst',
    hasIcon: true,
    icon: AccountIcon,
    linkProps: { href: 'https://pingidentity.com/' },
  },
  {
    email: 'ajinaa@mapquest.com',
    firstName: 'Kaycee',
    lastName: 'Jina',
    hasIcon: true,
    icon: AccountIcon,
    linkProps: { href: 'https://pingidentity.com/' },
  },
  {
    email: 'vmalster4@biblegateway.com',
    firstName: 'Lorry',
    lastName: 'Malster',
    hasIcon: true,
    icon: AccountIcon,
    linkProps: { href: 'https://pingidentity.com/' },
  },
  {
    email: 'yphipp6@yellowpages.com',
    firstName: 'Stanley',
    lastName: 'Phipp',
    hasIcon: true,
    icon: AccountIcon,
    linkProps: { href: 'https://pingidentity.com/' },
  },
  {
    email: 'mskilbeck3@bbc.co.uk',
    firstName: 'Gradey',
    lastName: 'Skilbeck',
    hasIcon: true,
    icon: AccountIcon,
    linkProps: { href: 'https://pingidentity.com/' },
  },
  {
    email: 'dstebbing1@msu.edu',
    firstName: 'Marnia',
    lastName: 'Stebbing',
    hasIcon: true,
    icon: AccountIcon,
    linkProps: { href: 'https://pingidentity.com/' },
  },
  {
    email: 'lsterley7@lulu.com',
    firstName: 'Joshua',
    lastName: 'Sterley',
    hasIcon: true,
    icon: AccountIcon,
    linkProps: { href: 'https://pingidentity.com/' },
  },
  {
    email: 'luttleyb@hugedomains.com',
    firstName: 'Jarrod',
    lastName: 'Uttley',
    hasIcon: true,
    icon: AccountIcon,
    linkProps: { href: 'https://pingidentity.com/' },
  },
  {
    email: 'lidelc@yelp.com',
    firstName: 'Andromache',
    lastName: 'Idel',
    hasIcon: true,
    icon: AccountIcon,
    linkProps: { href: 'https://pingidentity.com/' },
  },
];
