image: node:8

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  tags:
    - platform-publish-node-fragment
    - platform-build-node-ui-page
    - platform-build-node-fragment
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  tags:
    - platform-publish-node-fragment
    - platform-build-node-ui-page
    - platform-build-node-fragment
  script: npm run build